import { useEffect, useRef, useState } from "react";
import { ArrowUpRight, Check, Copy, Download, Github, Linkedin, Menu, MousePointer2, Send, X } from "lucide-react";
import { profile, type Locale } from "@/data/profile";

function SignalField() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const pointer = useRef({ x: 0, y: 0 });
  useEffect(() => {
    const canvas = canvasRef.current;
    const context = canvas?.getContext("2d");
    if (!canvas || !context) return;
    const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    const particles = Array.from({ length: window.innerWidth < 700 ? 34 : 72 }, (_, index) => ({ x: (index * 97) % 1000, y: (index * 53) % 700, speed: 0.0006 + (index % 5) * 0.00015, radius: index % 7 === 0 ? 2 : 1 }));
    let frame = 0;
    const resize = () => { const ratio = Math.min(window.devicePixelRatio || 1, 1.5); canvas.width = canvas.clientWidth * ratio; canvas.height = canvas.clientHeight * ratio; context.setTransform(ratio, 0, 0, ratio, 0, 0); };
    const draw = (time: number) => {
      const width = canvas.clientWidth; const height = canvas.clientHeight; context.clearRect(0, 0, width, height);
      const pointerX = pointer.current.x || width * 0.72; const pointerY = pointer.current.y || height * 0.4;
      particles.forEach((particle, index) => { const x = (particle.x / 1000) * width; const y = (particle.y / 700) * height; const glow = Math.max(0, 1 - Math.hypot(pointerX - x, pointerY - y) / 230); context.beginPath(); context.arc(x, y, particle.radius + glow * 2.5, 0, Math.PI * 2); context.fillStyle = glow > 0.1 ? `rgba(198, 255, 92, ${0.3 + glow * 0.7})` : "rgba(185, 193, 176, .34)"; context.fill(); if (index % 4 === 0 && glow > 0.02) { context.beginPath(); context.moveTo(x, y); context.lineTo(pointerX, pointerY); context.strokeStyle = `rgba(198, 255, 92, ${glow * 0.12})`; context.stroke(); } if (!reduceMotion) particle.x = (particle.x + time * particle.speed) % 1040; });
      if (!reduceMotion) frame = requestAnimationFrame(draw);
    };
    const onMove = (event: MouseEvent) => { const rect = canvas.getBoundingClientRect(); pointer.current = { x: event.clientX - rect.left, y: event.clientY - rect.top }; };
    resize(); draw(0); if (!reduceMotion) frame = requestAnimationFrame(draw); window.addEventListener("resize", resize); canvas.addEventListener("mousemove", onMove);
    return () => { cancelAnimationFrame(frame); window.removeEventListener("resize", resize); canvas.removeEventListener("mousemove", onMove); };
  }, []);
  return <canvas ref={canvasRef} className="signal-field" aria-hidden="true" />;
}

function MagneticLink({ children, href, className = "" }: { children: React.ReactNode; href: string; className?: string }) {
  const ref = useRef<HTMLAnchorElement>(null);
  const move = (event: React.MouseEvent<HTMLAnchorElement>) => { if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return; const element = ref.current; if (!element) return; const rect = element.getBoundingClientRect(); element.style.transform = `translate(${(event.clientX - rect.left - rect.width / 2) * 0.12}px, ${(event.clientY - rect.top - rect.height / 2) * 0.12}px)`; };
  return <a ref={ref} href={href} onMouseMove={move} onMouseLeave={() => { if (ref.current) ref.current.style.transform = "translate(0, 0)"; }} className={`magnetic ${className}`}>{children}</a>;
}

export default function Portfolio() {
  const [locale, setLocale] = useState<Locale>("en"); const [menuOpen, setMenuOpen] = useState(false); const [intro, setIntro] = useState(true); const [copied, setCopied] = useState(""); const t = profile.labels[locale];
  useEffect(() => { const timeout = window.setTimeout(() => setIntro(false), 720); return () => window.clearTimeout(timeout); }, []);
  const copy = async (value: string) => { await navigator.clipboard.writeText(value); setCopied(value); window.setTimeout(() => setCopied(""), 1400); };
  const navIds = ["about", "skills", "work", "experience", "contact"];
  return <div className="portfolio-shell">
    <div className={`intro-screen ${intro ? "is-visible" : ""}`} aria-hidden={!intro}><span>MKC</span><i /></div><div className="cursor-dot" aria-hidden="true"><MousePointer2 size={14} /></div>
    <header className="site-header"><a href="#top" className="brand-mark">MKC<span>.</span></a><nav className={menuOpen ? "open" : ""} aria-label="Main navigation">{t.nav.map((item, index) => <a key={item} href={`#${navIds[index]}`} onClick={() => setMenuOpen(false)}>{item}</a>)}</nav><div className="header-actions"><button className="lang-switch" onClick={() => setLocale(locale === "en" ? "fr" : "en")} aria-label="Switch language">{locale === "en" ? "FR" : "EN"}</button><a className="header-contact" href="#contact">{t.contact}<ArrowUpRight size={15} /></a><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button></div></header>
    <main id="top">
      <section className="hero-section" aria-labelledby="hero-title"><SignalField /><div className="hero-grid-lines" aria-hidden="true" /><div className="hero-content"><p className="eyebrow reveal">{profile.location} <span>·</span> available for meaningful work</p><h1 id="hero-title" className="hero-title reveal delay-1">I make complex<br /><em>things connect.</em></h1><p className="hero-role reveal delay-2">{profile.name}<br /><strong>{profile.role}</strong> · {profile.disciplines}</p><div className="hero-actions reveal delay-3"><MagneticLink href={profile.cv} className="button button-primary"><Download size={17} /> {t.viewCv}</MagneticLink><MagneticLink href="#contact" className="button button-quiet">{t.contact} <ArrowUpRight size={17} /></MagneticLink></div><div className="hero-award reveal delay-4"><span className="award-pulse" />{profile.heroAward}</div></div><div className="hero-index" aria-hidden="true">01 <span>/</span> 08</div><a className="scroll-cue" href="#about"><span>{t.scroll}</span><i /></a></section>
      <section id="about" className="section about-section content-grid"><div className="section-label">{t.about}</div><div className="about-main"><p className="big-copy">{profile.intro}</p><p className="body-copy">{profile.about}</p><div className="about-meta"><span>{profile.location}</span><span>82+ WPM</span><span>{profile.languages.join(" · ")}</span></div></div><div className="portrait-wrap"><img src={profile.photo} alt={`${profile.name}, IT Technician and Full-Stack Developer`} /><span className="portrait-caption">The person behind the signal</span></div></section>
      <section id="skills" className="section skills-section"><div className="section-heading"><div className="section-label">{t.skills}</div><h2>From first<br /><em>signal</em> to scale.</h2></div><div className="skills-list">{profile.skills.map((skill, index) => <span key={skill} style={{ "--i": index } as React.CSSProperties}>{skill}</span>)}</div></section>
      <section id="work" className="section feature-section"><div className="section-label">{t.featured} <span>01</span></div><div className="feature-intro"><h2>{profile.featuredProject.title}</h2><p>{profile.featuredProject.summary}</p><div className="tag-row">{profile.featuredProject.stack.map(tag => <span key={tag}>{tag}</span>)}</div></div><div className="feature-visual"><div className="visual-placeholder"><span>[ADD SCREENSHOT]</span><div className="farm-grid"><i /><i /><i /><i /><i /><i /></div><div className="sensor-dot" /></div></div><div className="case-study-grid">{[[t.problem, profile.featuredProject.problem], [t.build, profile.featuredProject.build], [t.challenge, profile.featuredProject.challenge], [t.result, profile.featuredProject.result]].map(([title, text]) => <div key={title}><h3>{title}</h3><p>{text}</p></div>)}</div><div className="architecture"><div className="architecture-top"><h3>{t.architecture}</h3><span>AG / 01</span></div><div className="arch-flow"><div><b>FIELD</b><span>Sensors<br />Telemetry</span></div><i>→</i><div><b>VISION</b><span>AI studio<br />Crop detection</span></div><i>→</i><div className="arch-active"><b>CONTROL</b><span>React Native<br />Valve control</span></div></div></div></section>
      <section className="section projects-section"><div className="section-heading inline-heading"><div className="section-label">{t.projects}</div><p>Systems made for the web, the team, and the next person who has to use them.</p></div><div className="project-grid">{profile.projects.map((project, index) => <article className="project-card" key={project.title}><div className="project-preview"><span>0{index + 2}</span><strong>[ADD SCREENSHOT]</strong><ArrowUpRight /></div><div className="project-card-body"><h3>{project.title}</h3><p>{project.description}</p><div className="tag-row">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="project-links"><a href="#contact">{t.live} <ArrowUpRight size={14} /></a><a href={profile.github} target="_blank" rel="noreferrer">{t.source} <Github size={14} /></a></div></div></article>)}</div></section>
      <section id="experience" className="section experience-section"><div className="section-heading"><div className="section-label">{t.experience}</div><h2>Growing with<br /><em>the work.</em></h2></div><div className="timeline">{profile.experience.map((item, index) => <article key={`${item.role}-${item.date}`} className={index === 0 ? "current" : ""}><time>{item.date}</time><div><h3>{item.role}</h3><p className="company">{item.company}</p><p>{item.detail}</p></div></article>)}</div></section>
      <section className="section recognition-section content-grid"><div className="section-label">{t.leadership}</div><div className="recognition-main"><div className="recognition-columns"><div><h3>Awards</h3>{profile.awards.map(item => <p key={item}>{item}</p>)}</div><div><h3>Leadership</h3>{profile.leadership.map(item => <p key={item}>{item}</p>)}</div><div><h3>Education</h3>{profile.education.map(item => <p key={item}><strong>{item.title}</strong><br />{item.detail}<br /><small>{item.date}</small></p>)}</div></div></div></section>
      <section id="contact" className="section contact-section"><div className="contact-top"><div className="section-label">08 / Contact</div><p>{t.contactBody}</p></div><h2>{t.contactTitle}<br /><em>Let's make it real.</em></h2><div className="contact-grid"><div className="contact-details"><div><span>Email</span><button onClick={() => copy(profile.email)}>{profile.email}{copied === profile.email ? <Check size={15} /> : <Copy size={15} />}</button></div><div><span>Phone</span><button onClick={() => copy(profile.phone)}>{profile.phone}{copied === profile.phone ? <Check size={15} /> : <Copy size={15} />}</button></div><div className="social-links"><a href={profile.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin /></a><a href={profile.github} target="_blank" rel="noreferrer" aria-label="GitHub"><Github /></a></div></div><form action="https://formspree.io/f/your-form-id" method="POST"><label>Name<input name="name" required placeholder="Your name" /></label><label>Email<input name="email" type="email" required placeholder="you@company.com" /></label><label>Message<textarea name="message" required rows={3} placeholder="What are you building?" /></label><button className="button button-primary" type="submit">{t.send} <Send size={16} /></button></form></div></section>
    </main><footer><span>© {new Date().getFullYear()} {profile.shortName}</span><span>Built between signals & systems</span><a href="#top">Back to top ↑</a></footer>
  </div>;
}